//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterOfCreativity.BaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CenterOfCreativityBaseEntities : DbContext
    {
        private static CenterOfCreativityBaseEntities _context;

        public CenterOfCreativityBaseEntities()
            : base("name=CenterOfCreativityBaseEntities")
        {
        }

        public static CenterOfCreativityBaseEntities GetContext()
        {
            if (_context == null)
            {
                _context = new CenterOfCreativityBaseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Visitors> Visitors { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
    }
}
