//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterOfCreativity.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int EventId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime Date { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int Id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
